DROP TABLE  IF EXISTS USER;

CREATE TABLE ID_USER(
    USER_ID INT NOT NULL PRIMARY KEY,
    UDERNAME VARCHAR (45) NOT NULL,
    FULLNAME VARCHAR(45) NOT NULL,
    PASSWORD VARCHAR(128) NOT NULL  
);

CREATE SEQUENCE PEOPLE;

ALTER TABLE ID_USER
ALTER COLUMN USER_ID
SET DEFAULT NEXTVAL ('PEOPLE');

UPDATE ID_USER
SET USER_ID = NEXTVAL ('PEOPLE');

INSERT INTO ID_USER (UDERNAME,FULLNAME, PASSWORD) VALUES ('vasco', 'vasco eti', 'pass');
 
